/**
 * Created by zhouhuafei on 2016/11/22.
 */
function Routes(opt){
    if(!opt||!opt.app){return;}
    this.app=opt.app;
    this.init();
}
Routes.prototype.init=function(){
    this.phoneHome();
    this.phoneLogin();
    this.phoneRegister();
};
Routes.prototype.phoneHome=function(){
    this.app.get('/phone/',function(req,res){
        res.render('phone/index',{num:2});
    })
};
Routes.prototype.phoneLogin=function(){
    this.app.get('/phone/login',function(req,res){
        res.end('<h1>欢迎来到我的登录页</h1>');
    })
};
Routes.prototype.phoneRegister=function(){
    this.app.get('/phone/register',function(req,res){
        res.end('<h1>欢迎来到我的注册页</h1>');
    })
};
module.exports=Routes;